import {createTranslation, Text} from "./texts";

const texts_fr: Record<Text, string> = {
    [Text.MY_COMPANY]: 'Mon Entreprise',
    [Text.MY_POTENTIAL]: 'Mon Potentiel',
    [Text.CONFIRM_ACTIVITY_SELECTION]: "Confirmation de la sélection de l'activité",
    [Text.CANNOT_ACTIVITY_SELECTION]: 'Vous devez sélectionner une activité',
    [Text.CONFIRM_DISCARD]: 'Confirmation de la défausse de %s carte(s)',
    [Text.CANNOT_DISCARD]: 'Vous devez défausser %s carte(s)',
    [Text.CONFIRM_DEVELOPMENT]: 'Confirmation du développement de %s produit(s)',
    [Text.CANNOT_DEVELOP_MAX_PRODUCT]: 'Vous ne pouvez pas développer plus de %s produit(s)',
    [Text.CANNOT_DEVELOP]: "Le nombre de cartes de potentiels utilisées doit être identique au nombre d'équipes sélectionnées",
    [Text.CONFIRM_DEPLOYMENT]: 'Confirmation du déploiement de %s produit(s)',
    [Text.CANNOT_DEPLOY]: 'Vous ne pouvez pas déployer plus de %s produit(s)',
    [Text.CONFIRM_CHOICE]: 'Confirmation de la sélection de %s amélioration',
    [Text.CANNOT_CHOICE]: "Vous ne pouvez pas sélectioner plus d'une amélioration",
    [Text.CONFIRM_PAYMENT]: "Confirmation du paiement de l'amélioration",
    [Text.CANNOT_PAYMENT]: 'Vous devez sélectionner les cartes correspondant au coût',
    [Text.COST]: 'Coût',
    [Text.SCORE]: 'Score',
    [Text.GAME_LEADER]: 'Meneur de jeu',
    [Text.LEADER_DESCRIPTION1]: 'Quand cette carte change de main, les joueurs doivent avoir au maximum six cartes en main.',
    [Text.LEADER_DESCRIPTION2]: 'Toutes les cartes supplémentaires sont défaussées.',
    [Text.BENEFIT]: 'Avantage',
    [Text.BONUS]: 'Bonus',
    [Text.EARNINGS]: 'Gains',
    [Text.ACTIVITY]: 'Activité',
    [Text.ACTIVITY_DEVELOPMENT_TITLE]: 'Développement',
    [Text.ACTIVITY_DEVELOPMENT_DESCRIPTION]: 'Chaque joueur peut développer un produit',
    [Text.ACTIVITY_DEVELOPMENT_PRIVILEGE]: 'L\'initiateur de l\'activité peut développer un produit supplémentaire',
    [Text.ACTIVITY_DEPLOYMENT_TITLE]: 'Déploiement',
    [Text.ACTIVITY_DEPLOYMENT_DESCRIPTION]: 'Chaque joueur peut déployer un produit',
    [Text.ACTIVITY_DEPLOYMENT_PRIVILEGE]: 'L\'initiateur de l\'activité peut déployer un produit supplémentaire',
    [Text.ACTIVITY_RETROSPECTIVE_TITLE]: 'Rétrospective',
    [Text.ACTIVITY_RETROSPECTIVE_DESCRIPTION]: 'Chaque joueur peut mettre en place une équipe ou une action d\'amélioration',
    [Text.ACTIVITY_RETROSPECTIVE_PRIVILEGE]: 'L\'initiateur de l\'activité paie une carte en moins',
    [Text.ACTIVITY_CONFERENCE_TITLE]: 'Conférence',
    [Text.ACTIVITY_CONFERENCE_DESCRIPTION]: 'Chaque joueur pioche deux cartes et en conserve une',
    [Text.ACTIVITY_CONFERENCE_PRIVILEGE]: 'L\'initiateur de l\'activité pioche non pas deux mais cinq cartes',
    [Text.ACTIVITY_COACH_TITLE]: 'Coach',
    [Text.ACTIVITY_COACH_DESCRIPTION]: 'L\'intervention du coach est limitée à l\'initiateur de l\'activité',
    [Text.ACTIVITY_COACH_PRIVILEGE]: 'L\'initiateur de l\'activité pioche une carte et la conserve',
    [Text.PRODUCT_TEAM]: 'Équipe Produit',
    [Text.PRODUCT_TEAM_ADVERGAME]: 'Jeux publicitaires',
    [Text.PRODUCT_TEAM_EDUCATION]: 'Jeux éducatifs',
    [Text.PRODUCT_TEAM_SOCIAL]: 'Jeux communautaires',
    [Text.PRODUCT_TEAM_MMOG]: 'Jeux en ligne massivement multijoueurs',
    [Text.AGILE_MATURITY]: 'Maturité Agile',
    [Text.AGILE_MATURITY_PASSIONATE_DEVELOPER_TITLE]: 'Développeur passionné',
    [Text.AGILE_MATURITY_PASSIONATE_DEVELOPER_DESCRIPTION]: 'Votre implication dans la communauté des développeurs facilite le recrutement.',
    [Text.AGILE_MATURITY_PASSIONATE_DEVELOPER_GAIN]: 'Vous payez une carte en moins pour former une équipe produit.',
    [Text.AGILE_MATURITY_AGILE_PRACTITIONER_TITLE]: 'Praticien agile',
    [Text.AGILE_MATURITY_AGILE_PRACTITIONER_DESCRIPTION]: 'Votre implication dans la communauté agile vous permet de profiter au mieux des rencontres entre pairs.',
    [Text.AGILE_MATURITY_AGILE_PRACTITIONER_GAIN]: 'Vous pouvez défausser des cartes de votre main à la place des cartes piochées.',
    [Text.AGILE_MATURITY_USER_EXPERIENCE_TITLE]: 'Expérience utilisateur',
    [Text.AGILE_MATURITY_USER_EXPERIENCE_DESCRIPTION]: 'Vous portez une attention particulière au métier des utilisateurs.',
    [Text.AGILE_MATURITY_USER_EXPERIENCE_GAIN]: 'Vous recevez une carte supplémentaire lors d’un déploiement d’au moins deux produits.',
    [Text.AGILE_MATURITY_PAIR_PROGRAMMING_TITLE]: 'Programmation en binôme',
    [Text.AGILE_MATURITY_PAIR_PROGRAMMING_DESCRIPTION]: 'Le développement systématique en binômes fluidifie les échanges entre vos développeurs.',
    [Text.AGILE_MATURITY_PAIR_PROGRAMMING_GAIN]: 'Vous piochez une carte lors d’un développement d’au moins deux produits.',
    [Text.AGILE_MATURITY_AGILE_ORGANIZER_TITLE]: 'Organisateur agile',
    [Text.AGILE_MATURITY_AGILE_ORGANIZER_DESCRIPTION]: 'Vous organisez des rencontres entre praticiens agiles ce qui vous permet de multiplier les échanges.',
    [Text.AGILE_MATURITY_AGILE_ORGANIZER_GAIN]: 'Vous conservez une carte supplémentaire parmi les cartes piochées.',
    [Text.AGILE_MATURITY_FEEDBACK_SESSIONS_TITLE]: 'Retour d’expérience',
    [Text.AGILE_MATURITY_FEEDBACK_SESSIONS_DESCRIPTION]: 'Vous apprenez à mieux vous connaître en analysant l’impact de vos décisions.',
    [Text.AGILE_MATURITY_FEEDBACK_SESSIONS_GAIN]: 'Vous piochez une carte après la mise en route d’une action d’amélioration.',
    [Text.AGILE_MATURITY_CLEAN_CODE_TITLE]: 'Code propre',
    [Text.AGILE_MATURITY_CLEAN_CODE_DESCRIPTION]: 'L’attention portée à la qualité de votre code vous permet de coder vite et bien.',
    [Text.AGILE_MATURITY_CLEAN_CODE_GAIN]: 'Vous développez un produit supplémentaire.',
    [Text.AGILE_MATURITY_CONTINUOUS_DELIVERY_TITLE]: 'Livraison en continu',
    [Text.AGILE_MATURITY_CONTINUOUS_DELIVERY_DESCRIPTION]: 'Votre produit est en permanence dans un état prêt à être livré.',
    [Text.AGILE_MATURITY_CONTINUOUS_DELIVERY_GAIN]: 'Vous déployez un produit supplémentaire.',
    [Text.AGILE_MATURITY_DEVOPS_TITLE]: 'DevOps',
    [Text.AGILE_MATURITY_DEVOPS_DESCRIPTION]: 'L’absence de barrières entre vos équipes fluidifie l’ensemble du cycle produit.',
    [Text.AGILE_MATURITY_DEVOPS_GAIN]: 'Vous pouvez payer avec des produits encore non déployés chacun ayant une valeur de 2 cartes.',
    [Text.AGILE_MATURITY_AGILE_HR_TITLE]: 'RH agile',
    [Text.AGILE_MATURITY_AGILE_HR_DESCRIPTION]: 'L’agilité de votre organisation interne augmente votre capacité d’action',
    [Text.AGILE_MATURITY_AGILE_HR_GAIN]: 'Vous pouvez avoir jusqu’à 10 cartes en mains lors du changement de meneur de jeu.',
    [Text.AGILE_MATURITY_ENGAGED_USERS_TITLE]: 'Utilisateurs impliqués',
    [Text.AGILE_MATURITY_ENGAGED_USERS_DESCRIPTION]: 'Vous impliquez vos utilisateurs dans le développement de vos produits.',
    [Text.AGILE_MATURITY_ENGAGED_USERS_GAIN]: 'Vous recevez une carte supplémentaire lors d’un déploiement.',
    [Text.AGILE_MATURITY_INTERNAL_COACH_TITLE]: 'Coach interne',
    [Text.AGILE_MATURITY_INTERNAL_COACH_DESCRIPTION]: 'Vous avez un coach en permanence disponible pour faire progresser vos équipes.',
    [Text.AGILE_MATURITY_INTERNAL_COACH_GAIN]: 'Vous payez une carte en moins pour mener une action d’amélioration.',
    [Text.AGILE_MATURITY_DETAILED_PLANNING_TITLE]: 'Planification détaillée',
    [Text.AGILE_MATURITY_DETAILED_PLANNING_DESCRIPTION]: 'La planification détaillée vous permet de prévoir le futur dans les moindres détails.',
    [Text.AGILE_MATURITY_TEST_TEAM_TITLE]: 'Equipe de test',
    [Text.AGILE_MATURITY_TEST_TEAM_DESCRIPTION]: 'Une équipe de test indépendante assure que les produits seront toujours conformes aux attentes.',
    [Text.AGILE_MATURITY_APPLICATION_FRAMEWORK_TITLE]: 'Framework applicatif',
    [Text.AGILE_MATURITY_APPLICATION_FRAMEWORK_DESCRIPTION]: 'L\’utilisation d’un framework applicatif augmente votre productivité en développement.',
    [Text.AGILE_MATURITY_AGILE_CERTIFICATION_TITLE]: 'Certification agile',
    [Text.AGILE_MATURITY_AGILE_CERTIFICATION_DESCRIPTION]: 'La certification de vos équipes garantit l\'adoption des valeurs, principes et pratiques agiles',
    [Text.AGILE_MATURITY_NEGATIVE_GAIN]: 'Cette carte est automatiquement ajoutée à votre entreprise si vous l\'avez en main à la fin du jeu.',
    [Text.AGILE_MATURITY_SOFTWARE_CRAFTSMANSHIP_TITLE]: 'Artisanat du logiciel',
    [Text.AGILE_MATURITY_SOFTWARE_CRAFTSMANSHIP_DESCRIPTION]: 'Vos développeurs sont animés par un professionalisme à toute épreuve.',
    [Text.AGILE_MATURITY_SOFTWARE_CRAFTSMANSHIP_GAIN]: 'Chaque équipe produit vous rapporte deux points supplémentaires.',
    [Text.AGILE_MATURITY_AGILE_SENSEI_TITLE]: 'Sensei agile',
    [Text.AGILE_MATURITY_AGILE_SENSEI_DESCRIPTION]: 'Vous êtes passé maître dans l’art de faire progresser vos équipes.',
    [Text.AGILE_MATURITY_AGILE_SENSEI_GAIN]: 'Chaque valeur ou action d’amélioration vous rapporte un point supplémentaire.',
    [Text.AGILE_MATURITY_PRODUCT_VISION_TITLE]: 'Vision produit',
    [Text.AGILE_MATURITY_PRODUCT_VISION_DESCRIPTION]: 'L’ensemble de votre stratégie est porté par une vision claire de vos produits.',
    [Text.AGILE_MATURITY_PRODUCT_VISION_GAIN]: 'Votre score final est majoré de 30 %.',
    [Text.AGILE_VALUE]: 'Valeur Agile',
    [Text.AGILE_VALUE_GAIN]: 'Chaque valeur adoptée donne droit à conserver une carte supplémentaire en début de tour.',
    [Text.AGILE_VALUE_HUMOR_TITLE]: 'Humour',
    [Text.AGILE_VALUE_HUMOR_DESCRIPTION]: 'L\'humour est-il une valeur agile ? Certains le pensent.',
    [Text.AGILE_VALUE_FEEDBACK_TITLE]: 'Feedback',
    [Text.AGILE_VALUE_FEEDBACK_DESCRIPTION]: 'Le feedback est une des valeurs mise en avant par Extreme Programming.',
    [Text.AGILE_VALUE_SIMPLICITY_TITLE]: 'Simplicité',
    [Text.AGILE_VALUE_SIMPLICITY_DESCRIPTION]: 'La simplicité est une des valeurs mise en avant par Extreme Programming.',
    [Text.AGILE_VALUE_TRUST_TITLE]: 'Confiance',
    [Text.AGILE_VALUE_TRUST_DESCRIPTION]: 'La confiance est une des valeurs mise en avant par Scrum.',
    [Text.AGILE_VALUE_TRANSPARENCY_TITLE]: 'Transparence',
    [Text.AGILE_VALUE_TRANSPARENCY_DESCRIPTION]: 'La transparence est une des valeurs mise en avant par Scrum.',
    [Text.AGILE_VALUE_COURAGE_TITLE]: 'Courage',
    [Text.AGILE_VALUE_COURAGE_DESCRIPTION]: 'Le courage est une valeur partagée par Scrum et Extreme Programming.',
    [Text.AGILE_VALUE_RESPECT_TITLE]: 'Respect',
    [Text.AGILE_VALUE_RESPECT_DESCRIPTION]: 'Le respect est une valeur partagée par Scrum et Extreme Programming.',
};

const translate_to_fr: Record<string, string> = createTranslation(texts_fr);

export function frTranslate(original: string) : string {
    return translate_to_fr[original] ?? original;
}
