import {getContext, setContext} from 'svelte';

export enum Text {
    COST,
    SCORE,
    GAME_LEADER,
    LEADER_DESCRIPTION1,
    LEADER_DESCRIPTION2,
    BENEFIT,
    BONUS,
    ACTIVITY,
    ACTIVITY_DEVELOPMENT_TITLE,
    ACTIVITY_DEVELOPMENT_DESCRIPTION,
    ACTIVITY_DEVELOPMENT_PRIVILEGE,
    ACTIVITY_DEPLOYMENT_TITLE,
    ACTIVITY_DEPLOYMENT_DESCRIPTION,
    ACTIVITY_DEPLOYMENT_PRIVILEGE,
    ACTIVITY_RETROSPECTIVE_TITLE,
    ACTIVITY_RETROSPECTIVE_DESCRIPTION,
    ACTIVITY_RETROSPECTIVE_PRIVILEGE,
    ACTIVITY_CONFERENCE_TITLE,
    ACTIVITY_CONFERENCE_DESCRIPTION,
    ACTIVITY_CONFERENCE_PRIVILEGE,
    ACTIVITY_COACH_TITLE,
    ACTIVITY_COACH_DESCRIPTION,
    ACTIVITY_COACH_PRIVILEGE,
    PRODUCT_TEAM,
    PRODUCT_TEAM_ADVERGAME,
    PRODUCT_TEAM_EDUCATION,
    PRODUCT_TEAM_SOCIAL,
    PRODUCT_TEAM_MMOG,
    AGILE_MATURITY,
    AGILE_MATURITY_PASSIONATE_DEVELOPER_TITLE,
    AGILE_MATURITY_PASSIONATE_DEVELOPER_DESCRIPTION,
    AGILE_MATURITY_PASSIONATE_DEVELOPER_GAIN,
    AGILE_MATURITY_AGILE_PRACTITIONER_TITLE,
    AGILE_MATURITY_AGILE_PRACTITIONER_DESCRIPTION,
    AGILE_MATURITY_AGILE_PRACTITIONER_GAIN,
    AGILE_MATURITY_USER_EXPERIENCE_TITLE,
    AGILE_MATURITY_USER_EXPERIENCE_DESCRIPTION,
    AGILE_MATURITY_USER_EXPERIENCE_GAIN,
    AGILE_MATURITY_PAIR_PROGRAMMING_TITLE,
    AGILE_MATURITY_PAIR_PROGRAMMING_DESCRIPTION,
    AGILE_MATURITY_PAIR_PROGRAMMING_GAIN,
    AGILE_MATURITY_PRODUCT_VISION_TITLE,
    AGILE_MATURITY_PRODUCT_VISION_DESCRIPTION,
    AGILE_MATURITY_PRODUCT_VISION_GAIN,
    AGILE_VALUE,
    AGILE_VALUE_GAIN,
    AGILE_VALUE_SIMPLICITY_TITLE,
    AGILE_VALUE_SIMPLICITY_DESCRIPTION,
    AGILE_VALUE_TRANSPARENCY_TITLE,
    AGILE_VALUE_TRANSPARENCY_DESCRIPTION,
    AGILE_VALUE_COURAGE_TITLE,
    AGILE_VALUE_COURAGE_DESCRIPTION,
}

const texts: Record<Text, string> = {
    [Text.COST]: 'Cost',
    [Text.SCORE]: 'Score',
    [Text.GAME_LEADER]: 'Game Leader',
    [Text.LEADER_DESCRIPTION1]: 'When this card changes hands, players must have a maximum of six cards in hand.',
    [Text.LEADER_DESCRIPTION2]: 'Any additional cards are discarded.',
    [Text.BENEFIT]: 'Benefit',
    [Text.BONUS]: 'Bonus',
    [Text.ACTIVITY]: 'Activity',
    [Text.ACTIVITY_DEVELOPMENT_TITLE]: 'Development',
    [Text.ACTIVITY_DEVELOPMENT_DESCRIPTION]: 'Each player can develop a product',
    [Text.ACTIVITY_DEVELOPMENT_PRIVILEGE]: 'The activity initiator can develop one additional product',
    [Text.ACTIVITY_DEPLOYMENT_TITLE]: 'Deployment',
    [Text.ACTIVITY_DEPLOYMENT_DESCRIPTION]: 'Each player can deploy a product',
    [Text.ACTIVITY_DEPLOYMENT_PRIVILEGE]: 'The activity initiator can deploy one additional product',
    [Text.ACTIVITY_RETROSPECTIVE_TITLE]: 'Retrospective',
    [Text.ACTIVITY_RETROSPECTIVE_DESCRIPTION]: 'Each player can set up a team or an improvement action',
    [Text.ACTIVITY_RETROSPECTIVE_PRIVILEGE]: 'The activity initiator pays one less card',
    [Text.ACTIVITY_CONFERENCE_TITLE]: 'Conference',
    [Text.ACTIVITY_CONFERENCE_DESCRIPTION]: 'Each player draws two cards and keeps one',
    [Text.ACTIVITY_CONFERENCE_PRIVILEGE]: 'The activity initiator draws five cards instead of two',
    [Text.ACTIVITY_COACH_TITLE]: 'Coach',
    [Text.ACTIVITY_COACH_DESCRIPTION]: 'The coach\'s intervention is limited to the activity initiator',
    [Text.ACTIVITY_COACH_PRIVILEGE]: 'The activity initiator draws one card and keeps it',
    [Text.PRODUCT_TEAM]: 'Product Team',
    [Text.PRODUCT_TEAM_ADVERGAME]: 'Advertising games',
    [Text.PRODUCT_TEAM_EDUCATION]: 'Educational games',
    [Text.PRODUCT_TEAM_SOCIAL]: 'Social games',
    [Text.PRODUCT_TEAM_MMOG]: 'Massively multiplayer online games',
    [Text.AGILE_MATURITY]: 'Agile Maturity',
    [Text.AGILE_MATURITY_PASSIONATE_DEVELOPER_TITLE]: 'Passionate Developer',
    [Text.AGILE_MATURITY_PASSIONATE_DEVELOPER_DESCRIPTION]: 'Your involvement in the developer community facilitates recruitment.',
    [Text.AGILE_MATURITY_PASSIONATE_DEVELOPER_GAIN]: 'You pay one less card to form a product team.',
    [Text.AGILE_MATURITY_AGILE_PRACTITIONER_TITLE]: 'Agile Practitioner',
    [Text.AGILE_MATURITY_AGILE_PRACTITIONER_DESCRIPTION]: 'Your involvement in the agile community allows you to make the most of peer-to-peer meetings.',
    [Text.AGILE_MATURITY_AGILE_PRACTITIONER_GAIN]: 'You can discard cards from your hand instead of drawn cards.',
    [Text.AGILE_MATURITY_USER_EXPERIENCE_TITLE]: 'User Experience',
    [Text.AGILE_MATURITY_USER_EXPERIENCE_DESCRIPTION]: 'You pay particular attention to user business needs.',
    [Text.AGILE_MATURITY_USER_EXPERIENCE_GAIN]: 'You receive an extra card when deploying at least two products.',
    [Text.AGILE_MATURITY_PAIR_PROGRAMMING_TITLE]: 'Pair Programming',
    [Text.AGILE_MATURITY_PAIR_PROGRAMMING_DESCRIPTION]: 'Systematic pair programming improves communication among your developers.',
    [Text.AGILE_MATURITY_PAIR_PROGRAMMING_GAIN]: 'You draw a card when developing at least two products.',
    [Text.AGILE_MATURITY_PRODUCT_VISION_TITLE]: 'Product Vision',
    [Text.AGILE_MATURITY_PRODUCT_VISION_DESCRIPTION]: 'Your strategy is underpinned by a clear vision of your products.',
    [Text.AGILE_MATURITY_PRODUCT_VISION_GAIN]: 'Your final score is increased by 30%.',
    [Text.AGILE_VALUE]: 'Agile Value',
    [Text.AGILE_VALUE_GAIN]: 'Each adopted value grants the right to keep an additional card at the beginning of a turn.',
    [Text.AGILE_VALUE_SIMPLICITY_TITLE]: 'Simplicity',
    [Text.AGILE_VALUE_SIMPLICITY_DESCRIPTION]: 'Simplicity is one of the values emphasized by Extreme Programming.',
    [Text.AGILE_VALUE_TRANSPARENCY_TITLE]: 'Transparency',
    [Text.AGILE_VALUE_TRANSPARENCY_DESCRIPTION]: 'Transparency is one of the values emphasized by Scrum.',
    [Text.AGILE_VALUE_COURAGE_TITLE]: 'Courage',
    [Text.AGILE_VALUE_COURAGE_DESCRIPTION]: 'Courage is a value shared by Scrum and Extreme Programming.',
};

export function setTextContext() {
    setContext('texts', texts);
}

export function _(key: Text): string {
    // const texts = getContext('texts');
    return texts[key];
}