import {BGA} from "./BGA";

export enum Text {
    MY_COMPANY,
    MY_POTENTIAL,
    CONFIRM_DISCARD,
    CANNOT_DISCARD,
    CONFIRM_DEVELOPMENT,
    CANNOT_DEVELOP_MAX_PRODUCT,
    CANNOT_DEVELOP,
    CONFIRM_DEPLOYMENT,
    CANNOT_DEPLOY,
    CONFIRM_CHOOSE_IMPROVEMENT,
    CANNOT_CHOOSE_IMPROVEMENT,
    COST,
    SCORE,
    GAME_LEADER,
    LEADER_DESCRIPTION1,
    LEADER_DESCRIPTION2,
    BENEFIT,
    BONUS,
    EARNINGS,
    ACTIVITY,
    ACTIVITY_DEVELOPMENT_TITLE,
    ACTIVITY_DEVELOPMENT_DESCRIPTION,
    ACTIVITY_DEVELOPMENT_PRIVILEGE,
    ACTIVITY_DEPLOYMENT_TITLE,
    ACTIVITY_DEPLOYMENT_DESCRIPTION,
    ACTIVITY_DEPLOYMENT_PRIVILEGE,
    ACTIVITY_RETROSPECTIVE_TITLE,
    ACTIVITY_RETROSPECTIVE_DESCRIPTION,
    ACTIVITY_RETROSPECTIVE_PRIVILEGE,
    ACTIVITY_CONFERENCE_TITLE,
    ACTIVITY_CONFERENCE_DESCRIPTION,
    ACTIVITY_CONFERENCE_PRIVILEGE,
    ACTIVITY_COACH_TITLE,
    ACTIVITY_COACH_DESCRIPTION,
    ACTIVITY_COACH_PRIVILEGE,
    PRODUCT_TEAM,
    PRODUCT_TEAM_ADVERGAME,
    PRODUCT_TEAM_EDUCATION,
    PRODUCT_TEAM_SOCIAL,
    PRODUCT_TEAM_MMOG,
    AGILE_MATURITY,
    AGILE_MATURITY_PASSIONATE_DEVELOPER_TITLE,
    AGILE_MATURITY_PASSIONATE_DEVELOPER_DESCRIPTION,
    AGILE_MATURITY_PASSIONATE_DEVELOPER_GAIN,
    AGILE_MATURITY_AGILE_PRACTITIONER_TITLE,
    AGILE_MATURITY_AGILE_PRACTITIONER_DESCRIPTION,
    AGILE_MATURITY_AGILE_PRACTITIONER_GAIN,
    AGILE_MATURITY_USER_EXPERIENCE_TITLE,
    AGILE_MATURITY_USER_EXPERIENCE_DESCRIPTION,
    AGILE_MATURITY_USER_EXPERIENCE_GAIN,
    AGILE_MATURITY_PAIR_PROGRAMMING_TITLE,
    AGILE_MATURITY_PAIR_PROGRAMMING_DESCRIPTION,
    AGILE_MATURITY_PAIR_PROGRAMMING_GAIN,
    AGILE_MATURITY_AGILE_ORGANIZER_TITLE,
    AGILE_MATURITY_AGILE_ORGANIZER_DESCRIPTION,
    AGILE_MATURITY_AGILE_ORGANIZER_GAIN,
    AGILE_MATURITY_FEEDBACK_SESSIONS_TITLE,
    AGILE_MATURITY_FEEDBACK_SESSIONS_DESCRIPTION,
    AGILE_MATURITY_FEEDBACK_SESSIONS_GAIN,
    AGILE_MATURITY_CLEAN_CODE_TITLE,
    AGILE_MATURITY_CLEAN_CODE_DESCRIPTION,
    AGILE_MATURITY_CLEAN_CODE_GAIN,
    AGILE_MATURITY_CONTINUOUS_DELIVERY_TITLE,
    AGILE_MATURITY_CONTINUOUS_DELIVERY_DESCRIPTION,
    AGILE_MATURITY_CONTINUOUS_DELIVERY_GAIN,
    AGILE_MATURITY_DEVOPS_TITLE,
    AGILE_MATURITY_DEVOPS_DESCRIPTION,
    AGILE_MATURITY_DEVOPS_GAIN,
    AGILE_MATURITY_AGILE_HR_TITLE,
    AGILE_MATURITY_AGILE_HR_DESCRIPTION,
    AGILE_MATURITY_AGILE_HR_GAIN,
    AGILE_MATURITY_ENGAGED_USERS_TITLE,
    AGILE_MATURITY_ENGAGED_USERS_DESCRIPTION,
    AGILE_MATURITY_ENGAGED_USERS_GAIN,
    AGILE_MATURITY_INTERNAL_COACH_TITLE,
    AGILE_MATURITY_INTERNAL_COACH_DESCRIPTION,
    AGILE_MATURITY_INTERNAL_COACH_GAIN,
    AGILE_MATURITY_DETAILED_PLANNING_TITLE,
    AGILE_MATURITY_DETAILED_PLANNING_DESCRIPTION,
    AGILE_MATURITY_TEST_TEAM_TITLE,
    AGILE_MATURITY_TEST_TEAM_DESCRIPTION,
    AGILE_MATURITY_APPLICATION_FRAMEWORK_TITLE,
    AGILE_MATURITY_APPLICATION_FRAMEWORK_DESCRIPTION,
    AGILE_MATURITY_AGILE_CERTIFICATION_TITLE,
    AGILE_MATURITY_AGILE_CERTIFICATION_DESCRIPTION,
    AGILE_MATURITY_NEGATIVE_GAIN,
    AGILE_MATURITY_SOFTWARE_CRAFTSMANSHIP_TITLE,
    AGILE_MATURITY_SOFTWARE_CRAFTSMANSHIP_DESCRIPTION,
    AGILE_MATURITY_SOFTWARE_CRAFTSMANSHIP_GAIN,
    AGILE_MATURITY_AGILE_SENSEI_TITLE,
    AGILE_MATURITY_AGILE_SENSEI_DESCRIPTION,
    AGILE_MATURITY_AGILE_SENSEI_GAIN,
    AGILE_MATURITY_PRODUCT_VISION_TITLE,
    AGILE_MATURITY_PRODUCT_VISION_DESCRIPTION,
    AGILE_MATURITY_PRODUCT_VISION_GAIN,
    AGILE_VALUE,
    AGILE_VALUE_GAIN,
    AGILE_VALUE_HUMOR_TITLE,
    AGILE_VALUE_HUMOR_DESCRIPTION,
    AGILE_VALUE_FEEDBACK_TITLE,
    AGILE_VALUE_FEEDBACK_DESCRIPTION,
    AGILE_VALUE_SIMPLICITY_TITLE,
    AGILE_VALUE_SIMPLICITY_DESCRIPTION,
    AGILE_VALUE_TRUST_TITLE,
    AGILE_VALUE_TRUST_DESCRIPTION,
    AGILE_VALUE_TRANSPARENCY_TITLE,
    AGILE_VALUE_TRANSPARENCY_DESCRIPTION,
    AGILE_VALUE_COURAGE_TITLE,
    AGILE_VALUE_COURAGE_DESCRIPTION,
    AGILE_VALUE_RESPECT_TITLE,
    AGILE_VALUE_RESPECT_DESCRIPTION,
}

const texts: Record<Text, string> = {
    [Text.MY_COMPANY]: 'My Company',
    [Text.MY_POTENTIAL]: 'My Potential',
    [Text.CONFIRM_DISCARD]: 'Confirm discarding %s card(s)',
    [Text.CANNOT_DISCARD]: 'You must discard %s card(s)',
    [Text.CONFIRM_DEVELOPMENT]: 'Confirm development of %s product(s)',
    [Text.CANNOT_DEVELOP_MAX_PRODUCT]: 'You cannot develop more than %s product(s)',
    [Text.CANNOT_DEVELOP]: 'Numbers of selected teams and discarded potential must match',
    [Text.CONFIRM_DEPLOYMENT]: 'Confirm deployment of %s product(s)',
    [Text.CANNOT_DEPLOY]: 'Cannot deploy more than %s product(s)',
    [Text.CONFIRM_CHOOSE_IMPROVEMENT]: 'Confirm selection of %s improvement',
    [Text.CANNOT_CHOOSE_IMPROVEMENT]: 'Cannot select more than one improvement',
    [Text.COST]: 'Cost',
    [Text.SCORE]: 'Score',
    [Text.GAME_LEADER]: 'Game Leader',
    [Text.LEADER_DESCRIPTION1]: 'When this card changes hands, players must have a maximum of six cards in hand.',
    [Text.LEADER_DESCRIPTION2]: 'Any additional cards are discarded.',
    [Text.BENEFIT]: 'Benefit',
    [Text.BONUS]: 'Bonus',
    [Text.EARNINGS]: 'Earnings',
    [Text.ACTIVITY]: 'Activity',
    [Text.ACTIVITY_DEVELOPMENT_TITLE]: 'Development',
    [Text.ACTIVITY_DEVELOPMENT_DESCRIPTION]: 'Each player can develop a product',
    [Text.ACTIVITY_DEVELOPMENT_PRIVILEGE]: 'The activity initiator can develop one additional product',
    [Text.ACTIVITY_DEPLOYMENT_TITLE]: 'Deployment',
    [Text.ACTIVITY_DEPLOYMENT_DESCRIPTION]: 'Each player can deploy a product',
    [Text.ACTIVITY_DEPLOYMENT_PRIVILEGE]: 'The activity initiator can deploy one additional product',
    [Text.ACTIVITY_RETROSPECTIVE_TITLE]: 'Retrospective',
    [Text.ACTIVITY_RETROSPECTIVE_DESCRIPTION]: 'Each player can set up a team or an improvement action',
    [Text.ACTIVITY_RETROSPECTIVE_PRIVILEGE]: 'The activity initiator pays one less card',
    [Text.ACTIVITY_CONFERENCE_TITLE]: 'Conference',
    [Text.ACTIVITY_CONFERENCE_DESCRIPTION]: 'Each player draws two cards and keeps one',
    [Text.ACTIVITY_CONFERENCE_PRIVILEGE]: 'The activity initiator draws five cards instead of two',
    [Text.ACTIVITY_COACH_TITLE]: 'Coach',
    [Text.ACTIVITY_COACH_DESCRIPTION]: 'The coach\'s intervention is limited to the activity initiator',
    [Text.ACTIVITY_COACH_PRIVILEGE]: 'The activity initiator draws one card and keeps it',
    [Text.PRODUCT_TEAM]: 'Product Team',
    [Text.PRODUCT_TEAM_ADVERGAME]: 'Advertising games',
    [Text.PRODUCT_TEAM_EDUCATION]: 'Educational games',
    [Text.PRODUCT_TEAM_SOCIAL]: 'Social games',
    [Text.PRODUCT_TEAM_MMOG]: 'Massively multiplayer online games',
    [Text.AGILE_MATURITY]: 'Agile Maturity',
    [Text.AGILE_MATURITY_PASSIONATE_DEVELOPER_TITLE]: 'Passionate Developer',
    [Text.AGILE_MATURITY_PASSIONATE_DEVELOPER_DESCRIPTION]: 'Your involvement in the developer community facilitates recruitment.',
    [Text.AGILE_MATURITY_PASSIONATE_DEVELOPER_GAIN]: 'You pay one less card to form a product team.',
    [Text.AGILE_MATURITY_AGILE_PRACTITIONER_TITLE]: 'Agile Practitioner',
    [Text.AGILE_MATURITY_AGILE_PRACTITIONER_DESCRIPTION]: 'Your involvement in the agile community allows you to make the most of peer-to-peer meetings.',
    [Text.AGILE_MATURITY_AGILE_PRACTITIONER_GAIN]: 'You can discard cards from your hand instead of drawn cards.',
    [Text.AGILE_MATURITY_USER_EXPERIENCE_TITLE]: 'User Experience',
    [Text.AGILE_MATURITY_USER_EXPERIENCE_DESCRIPTION]: 'You pay particular attention to user business needs.',
    [Text.AGILE_MATURITY_USER_EXPERIENCE_GAIN]: 'You receive an extra card when deploying at least two products.',
    [Text.AGILE_MATURITY_PAIR_PROGRAMMING_TITLE]: 'Pair Programming',
    [Text.AGILE_MATURITY_PAIR_PROGRAMMING_DESCRIPTION]: 'Systematic pair programming improves communication among your developers.',
    [Text.AGILE_MATURITY_PAIR_PROGRAMMING_GAIN]: 'You draw a card when developing at least two products.',
    [Text.AGILE_MATURITY_AGILE_ORGANIZER_TITLE]: 'Agile Organizer',
    [Text.AGILE_MATURITY_AGILE_ORGANIZER_DESCRIPTION]: 'You organize meetings among agile practitioners to enhance exchanges.',
    [Text.AGILE_MATURITY_AGILE_ORGANIZER_GAIN]: 'You keep one extra card among the drawn cards.',
    [Text.AGILE_MATURITY_FEEDBACK_SESSIONS_TITLE]: 'Feedback Sessions',
    [Text.AGILE_MATURITY_FEEDBACK_SESSIONS_DESCRIPTION]: 'You learn more about yourself by analyzing the impact of your decisions.',
    [Text.AGILE_MATURITY_FEEDBACK_SESSIONS_GAIN]: 'You draw a card after implementing an improvement action.',
    [Text.AGILE_MATURITY_CLEAN_CODE_TITLE]: 'Clean Code',
    [Text.AGILE_MATURITY_CLEAN_CODE_DESCRIPTION]: 'Attention to code quality allows you to code faster and better.',
    [Text.AGILE_MATURITY_CLEAN_CODE_GAIN]: 'You develop an additional product.',
    [Text.AGILE_MATURITY_CONTINUOUS_DELIVERY_TITLE]: 'Continuous Delivery',
    [Text.AGILE_MATURITY_CONTINUOUS_DELIVERY_DESCRIPTION]: 'Your product is always ready to be delivered.',
    [Text.AGILE_MATURITY_CONTINUOUS_DELIVERY_GAIN]: 'You deploy an additional product.',
    [Text.AGILE_MATURITY_DEVOPS_TITLE]: 'DevOps',
    [Text.AGILE_MATURITY_DEVOPS_DESCRIPTION]: 'Removing barriers between teams streamlines the product lifecycle.',
    [Text.AGILE_MATURITY_DEVOPS_GAIN]: 'You can pay with yet-to-be-deployed products, each valued at 2 cards.',
    [Text.AGILE_MATURITY_AGILE_HR_TITLE]: 'Agile HR',
    [Text.AGILE_MATURITY_AGILE_HR_DESCRIPTION]: 'The agility of your internal organization increases your capacity for action.',
    [Text.AGILE_MATURITY_AGILE_HR_GAIN]: 'You can hold up to 10 cards when changing the game leader.',
    [Text.AGILE_MATURITY_ENGAGED_USERS_TITLE]: 'Engaged Users',
    [Text.AGILE_MATURITY_ENGAGED_USERS_DESCRIPTION]: 'You involve your users in product development.',
    [Text.AGILE_MATURITY_ENGAGED_USERS_GAIN]: 'You receive an extra card during deployment.',
    [Text.AGILE_MATURITY_INTERNAL_COACH_TITLE]: 'Internal Coach',
    [Text.AGILE_MATURITY_INTERNAL_COACH_DESCRIPTION]: 'A coach is always available to improve your teams.',
    [Text.AGILE_MATURITY_INTERNAL_COACH_GAIN]: 'You pay one less card to carry out an improvement action.',
    [Text.AGILE_MATURITY_DETAILED_PLANNING_TITLE]: 'Detailed Planning',
    [Text.AGILE_MATURITY_DETAILED_PLANNING_DESCRIPTION]: 'Detailed planning allows you to predict the future with precision.',
    [Text.AGILE_MATURITY_TEST_TEAM_TITLE]: 'Test Team',
    [Text.AGILE_MATURITY_TEST_TEAM_DESCRIPTION]: 'An independent test team ensures products always meet expectations.',
    [Text.AGILE_MATURITY_APPLICATION_FRAMEWORK_TITLE]: 'Application Framework',
    [Text.AGILE_MATURITY_APPLICATION_FRAMEWORK_DESCRIPTION]: 'Using an application framework boosts your development productivity.',
    [Text.AGILE_MATURITY_AGILE_CERTIFICATION_TITLE]: 'Agile Certification',
    [Text.AGILE_MATURITY_AGILE_CERTIFICATION_DESCRIPTION]: 'Certifying your teams ensures adoption of agile values, principles, and practices.',
    [Text.AGILE_MATURITY_NEGATIVE_GAIN]: 'This card is automatically added to your company if it\'s in your hand at the end of the game.',
    [Text.AGILE_MATURITY_SOFTWARE_CRAFTSMANSHIP_TITLE]: 'Software Craftsmanship',
    [Text.AGILE_MATURITY_SOFTWARE_CRAFTSMANSHIP_DESCRIPTION]: 'Your developers are driven by unyielding professionalism.',
    [Text.AGILE_MATURITY_SOFTWARE_CRAFTSMANSHIP_GAIN]: 'Each product team earns you two additional points at the end of the game.',
    [Text.AGILE_MATURITY_AGILE_SENSEI_TITLE]: 'Agile Sensei',
    [Text.AGILE_MATURITY_AGILE_SENSEI_DESCRIPTION]: 'You have mastered the art of advancing your teams.',
    [Text.AGILE_MATURITY_AGILE_SENSEI_GAIN]: 'Each value or improvement action earns you one additional point at the end of the game.',
    [Text.AGILE_MATURITY_PRODUCT_VISION_TITLE]: 'Product Vision',
    [Text.AGILE_MATURITY_PRODUCT_VISION_DESCRIPTION]: 'Your strategy is underpinned by a clear vision of your products.',
    [Text.AGILE_MATURITY_PRODUCT_VISION_GAIN]: 'Your final score is increased by 30%.',
    [Text.AGILE_VALUE]: 'Agile Value',
    [Text.AGILE_VALUE_GAIN]: 'Each adopted value grants the right to keep an additional card at the beginning of a turn.',
    [Text.AGILE_VALUE_HUMOR_TITLE]: 'Humor',
    [Text.AGILE_VALUE_HUMOR_DESCRIPTION]: 'Is humor an agile value? Some think so.',
    [Text.AGILE_VALUE_FEEDBACK_TITLE]: 'Feedback',
    [Text.AGILE_VALUE_FEEDBACK_DESCRIPTION]: 'Feedback is one of the values emphasized by Extreme Programming.',
    [Text.AGILE_VALUE_SIMPLICITY_TITLE]: 'Simplicity',
    [Text.AGILE_VALUE_SIMPLICITY_DESCRIPTION]: 'Simplicity is one of the values emphasized by Extreme Programming.',
    [Text.AGILE_VALUE_TRUST_TITLE]: 'Trust',
    [Text.AGILE_VALUE_TRUST_DESCRIPTION]: 'Trust is one of the values emphasized by Scrum.',
    [Text.AGILE_VALUE_TRANSPARENCY_TITLE]: 'Transparency',
    [Text.AGILE_VALUE_TRANSPARENCY_DESCRIPTION]: 'Transparency is one of the values emphasized by Scrum.',
    [Text.AGILE_VALUE_COURAGE_TITLE]: 'Courage',
    [Text.AGILE_VALUE_COURAGE_DESCRIPTION]: 'Courage is a value shared by Scrum and Extreme Programming.',
    [Text.AGILE_VALUE_RESPECT_TITLE]: 'Respect',
    [Text.AGILE_VALUE_RESPECT_DESCRIPTION]: 'Respect is a value shared by Scrum and Extreme Programming.',

};

function localFormat(template: string, args: string[]) : string {
    return template.replace(/%s/g, () => args.shift());
}

export function _(templateKey: Text, ...args: string[]): string {
    const template = BGA.translate(texts[templateKey]);
    if(args.length === 0)
        return template;
    return localFormat(template, args);
}